version: "3.8"
services:

  redis:
    image: redis:alpine
    ports:
      - "4279:3279"
    restart: always
    volumes:
      - 'redisdata:/data'
    networks:
      - backend

  postgres:
    image: postgres:alpine
    ports:
      - "56432:5432"
    env_file:
        - app.env
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  worker:
    build: .
    command: celery -A app.tasks worker -B -l INFO
    env_file:
      - app.env
    depends_on:
      - postgres
      - redis
    restart: always
    networks:
      - backend

  app:
    build: .
    environment:
     - PYTHONUNBUFFERED=1
    env_file:
      - app.env
    ports:
      - '8000:8000'
    # restart: always
    depends_on:
      - redis
      - postgres
    networks:
      - backend

volumes:
  postgres_data:
  redisdata:

networks:
  backend: